### YamlMime:Landing

title: Azure Monitor troubleshooting documentation # < 60 chars
summary: Welcome to Azure Monitor troubleshooting. These articles explain how to determine, diagnose, and fix issues that you might encounter when you use Azure Monitor. In the navigation pane on the left, browse through the article list or use the search box to find issues and solutions.
metadata:
  title: Troubleshoot Azure Monitor issues
  description: Documentation for troubleshooting common issues with Azure Monitor. # Required; article description that is displayed in search results. < 160 chars.
  ms.service: azure-monitor  #Required; service per approved list. service slug assigned to your service by ACOM.
  ms.topic: landing-page # Required
  author: genlin  #Required; your GitHub user alias, with correct capitalization.
  ms.author: genli #Required; microsoft alias of author; optional team alias.
  ms.date: 5/6/2022

# linkListType: architecture | concept | deploy | download | get-started | how-to-guide | learn | overview | quickstart | reference | tutorial | video | whats-new

landingContent:

 # Card
  - title: Troubleshooting Azure Application Insights issues
    linkLists:
      - linkListType: how-to-guide
        links:
          - text: Error retrieving data in portal
            url: ./troubleshoot-portal-connectivity.md
          - text: Missing CPU Total and Committed Memory metrics
            url: ./missing-cpu-total-committed-memory-metrics.md
          - text: Troubleshooting auto-instrumentation issues
            url: ./auto-instrumentation-troubleshoot.md
