name: Manage stale branches

permissions:
  contents: write
      
on:
  workflow_dispatch:
  

jobs:

  stale-branch:
    if: github.repository_owner == 'MicrosoftDocs'
    uses: MicrosoftDocs/microsoft-365-docs/.github/workflows/Shared-StaleBranch.yml@workflows-prod
    with:
        PayloadJson: ${{ toJSON(github) }}
        RepoBranchSkipList: '[
                              "automation"
                             ]'
        ReportOnly: false
    secrets:
        AccessToken: ${{ secrets.GITHUB_TOKEN }}