name: Validate branch names

on:
  create

jobs:
  validate-branch-name:
    if: github.repository == 'MicrosoftDocs/SupportArticles-docs-pr' && startsWith(github.ref, 'refs/heads/')
    runs-on: windows-latest
    strategy:
      fail-fast: true # Prevent retries on failure
    steps:
      - name: Set git to use long paths
        run: git config --system core.longpaths true
      - name: Try checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
