name: Validate branch names

on:
  create

jobs:
  validate-branch-name:
    if: github.repository == 'MicrosoftDocs/SupportArticles-docs-pr' && startsWith(github.ref, 'refs/heads/')
    runs-on: windows-latest
    strategy:
      fail-fast: true # Prevent retries on failure
    steps:
      - name: Set git to use long paths
        run: git config --system core.longpaths true
      - name: Try checkout
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
